- become: yes
  hosts: all
  name: foundry-setup
  tasks:
    - name: Add the user 'foundry-user' and add it to 'sudo'
      user:
        name: foundry-user
        group: sudo

    - name: Add SSH key to 'foundry-user'
      authorized_key:
        user: foundry-user
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Wait for apt to unlock
      become: yes
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Create a foundry data directory
      ansible.builtin.file:
        path: /home/foundry-user/foundry/data
        state: directory

    # - name: Copy foundry data directory zip to foundry data directory
    #   ansible.builtin.copy:
    #     src: ./example-file-to-copy.txt
    #     dest: /home/foundry-user/foundry/data
    #     owner: foundry-user
    #     mode: "0644"

    # TODO: Run Foundry
    - name: Execute the command in remote shell; stdout goes to the specified file on the remote
      ansible.builtin.shell: |
        docker run \
        -d \
        --env FOUNDRY_RELEASE_URL='{{ foundry_timed_url}}' \
        --publish 30000:30000/tcp \
        --volume /home/foundry-user/foundry/data:/data \
        --restart always \
        felddy/foundryvtt:release
